import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Leftbar from "@/components/Leftbar";
import Rightbar from "@/components/Rightbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl xxl:max-w-xxl mx-auto flex justify-between">
          <div className="px-2 xsm:px-4 xxl-px-8"><Leftbar/></div>
          <div className="flex-1 lg:max-w-[600px] border-x-[1px] border-borderGray">{children}</div>
          <div className="hidden lg:flex ml-4 xl:ml-8 flex-1 bg-red-200"><Rightbar/></div>
        </div>
      </body>
    </html>
  );
}
